sudo: required
cache: 
  directories: 
    - "$HOME/.m2"

language: java
jdk:
  - oraclejdk8
#  - oraclejdk7
#  - openjdk7

before_script:
  - echo "MAVEN_OPTS='-Xmx1024m -XX:MaxPermSize=256m'" > ~/.mavenrc
after_success:
  - mvn clean cobertura:cobertura coveralls:report -DrepoToken="${COVERALLS_REPO_TOKEN}"

install: travis_wait 30 mvn install
