baseURL = "http://shardingsphere.io/document/cn/"
canonifyurls = true
languageCode = "en-us"
title = "Sharding-Sphere"
theme = "hugo-theme-learn"
[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "black"
  # Disable search function. It will hide search bar
  disableSearch = true
