name: build docs PDF
on:
  push:
    branches:
    - master
    paths:
    - 'docs/document/content/**'
jobs:
  build:
    # instal dependencies
    name: publish PDF
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        sudo apt-get update -y 
        sudo apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
        sudo apt-get install texlive-xetex latex-cjk-all
        sudo apt-get install pandoc
        wget https://github.com/adobe-fonts/source-han-sans/raw/release/OTF/SourceHanSansSC.zip
        wget https://github.com/adobe-fonts/source-han-serif/raw/release/OTF/SourceHanSerifSC_SB-H.zip
        wget https://github.com/adobe-fonts/source-han-serif/raw/release/OTF/SourceHanSerifSC_EL-M.zip
        unzip SourceHanSansSC.zip
        unzip SourceHanSerifSC_EL-M.zip
        unzip SourceHanSerifSC_SB-H.zip
        sudo mv SourceHanSansSC SourceHanSerifSC_EL-M SourceHanSerifSC_SB-H /usr/share/fonts/opentype/
        wget -O source-serif-pro.zip https://www.fontsquirrel.com/fonts/download/source-serif-pro
        unzip source-serif-pro -d source-serif-pro
        sudo mv source-serif-pro /usr/share/fonts/opentype/
        wget -O source-sans-pro.zip https://www.fontsquirrel.com/fonts/download/source-sans-pro
        unzip source-sans-pro -d source-sans-pro
        sudo mv source-sans-pro /usr/share/fonts/opentype/
        wget -O source-code-pro.zip https://www.fontsquirrel.com/fonts/download/source-code-pro
        unzip source-code-pro -d source-code-pro
        sudo mv source-code-pro /usr/share/fonts/opentype/
        sudo fc-cache -f -v
    - name: generate PDF
      run: |
        cd docs/document
        bash generatePDF.sh cn
        bash generatePDF.sh en
    - name: commit PDF
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add *.pdf -f
        git commit -m "Update PDF files"
        git push -u origin master